plugins {
    id 'ml-common'
    id 'net.neoforged.moddev'
}

neoForge {
    neoFormVersion = neoform_version

    def at = file('src/main/resources/META-INF/accesstransformer.cfg')
    if (at.exists()) accessTransformers = [at.absolutePath]

    parchment {
        minecraftVersion = "1.21.4"
        mappingsVersion = parchment_version
    }
}

dependencies {
    compileOnly group:'org.spongepowered', name:'mixin', version:'0.8.5'
    testmodCompileOnly sourceSets.main.output
}