plugins {
    id 'maven-publish'
}

publishing {
    def mavenRepo = System.getenv("MavenRepository") ?: null

    if (mavenRepo != null) {
        publications {
            mavenJava(MavenPublication) {
                artifactId = "${mod_id}-${project.name}"
                from components.java

                pom.withXml {
                    asNode().dependencies.each { it.replaceNode {} }
                }
            }
        }

        repositories {
            maven { url = mavenRepo + "/maven"}
        }

        def gitPushTask = tasks.register("gitPush") {
            group = 'publishing'
            description = 'Commits and pushes to the maven repository.'

            doLast {
                def execOps = project.services.get(ExecOperations)
                execOps.exec {
                    workingDir mavenRepo
                    commandLine 'cmd', '/c', 'git add . && git commit -m "' + "${mod_id}-${project.name} ${version}" + '" && git push'
                }
            }
        }

        tasks.named('publish').configure {
            finalizedBy(gitPushTask)
        }

    } else {
        println("Maven Repository isn't defined!")
    }
}