org.gradle.jvmargs=-Xmx8192M
org.gradle.deamon=false

# Project
version=4.1.0
group=net.morthen.resourceconfigapi
java_version=25
curseforge_id=975801
modrinth_id=69TY9iyJ

# Common
mod_name=Resource Config API
mod_author=Morthen
mod_id=resourceconfigapi
mod_license=MIT
mod_credits=
mod_description=Config API mainly for my own mods.

# Plugins
fabric_loom=1.17-SNAPSHOT
forge_gradle=7.0.30
moddev_gradle=2.0.141
mod_publish=2.0.1
mixin_version=0.8.7
mixin_extras=0.3.5

# Loader stuff
minecraft_version=26.1.2
neoform=26.1.2-1
fabric_api=0.153.0
fabric_loader=0.19.3
neoforge=26.1.2.76
forge=64.0.10

# Dependencies
mod_menu=18.0.0-beta.1
