org.gradle.jvmargs=-Xmx8192M
org.gradle.daemon=false

# Project
mod_version=3.6.1
group=net.xstopho.resourceconfigapi
java_version=21
curseforge_id=975801
modrinth_id=69TY9iyJ

# Common
mod_name=Resource Config API
mod_author=xStopho
mod_id=resourceconfigapi
mod_license=MIT
mod_description=Config API mainly for my own mods.