org.gradle.jvmargs=-Xmx8192M
org.gradle.daemon=false

version=4.1.1
group=net.morthen
java_version=25

modrinth_id=69TY9iyJ
curseforge_id=975801

# Common
minecraft_version=26.2

mod_id=resourceconfigapi
mod_name=Resource Config API
mod_author=Morthen
mod_license=MIT
mod_description=

neoform=26.2-2
neoforge=26.2.0.54-beta
fabric_api=0.156.0+26.2
fabric_loader=0.19.3
forge=65.1.0

# Additional stuff
sources_url=https://github.com/Morthen-Mods/Resource-Config-API
issues_url=https://github.com/Morthen-Mods/Resource-Config-API/issues