plugins {
    id 'loader'
    id 'net.minecraftforge.gradle'
    id 'org.spongepowered.mixin' version '0.7-SNAPSHOT'
}

dependencies {
    minecraft "net.minecraftforge:forge:${minecraft_version}-${forge}"
    implementation('net.sf.jopt-simple:jopt-simple:5.0.4') { version { strictly '5.0.4' } }

    testmodImplementation sourceSets.main.output
    testmodCompileOnly project(':latest:common').sourceSets.testmod.output
}

mixin {
    config("${mod_id}.mixins.json")
}

jar {
    manifest {
        attributes([
                'FMLCorePluginContainsFMLMod': 'true',
                'MixinConfigs': "${mod_id}.mixins.json"
        ])
    }
}

minecraft {
    mappings channel: 'official', version: minecraft_version

    def directory = project.projectDir.parent.split("\\\\").last()

    def at = file('../common/src/main/resources/META-INF/accesstransformer.cfg')
    if (at.exists()) accessTransformers = [at]

    runs {
        client {
            workingDirectory project.file('../fabric/runs/client')
            ideaModule "${rootProject.name}.${directory}.${project.name}.testmod"
            property 'eventbus.api.strictRuntimeChecks', 'true'
            taskName 'TestClient'
            mods {
                modClientRun {
                    source sourceSets.testmod
                }
            }
        }
    }
}


compileTestmodJava {
    source(project(':latest:common').sourceSets.testmod.allSource)
}

processTestmodResources {
    from project(':latest:common').sourceSets.testmod.resources
}

sourceSets.each {
    def dir = layout.buildDirectory.dir("sourcesSets/$it.name")
    it.output.resourcesDir = dir
    it.java.destinationDirectory = dir
}

publishMods {
    file = jar.archiveFile
    modLoaders.addAll("forge")
}