plugins {
    id 'ml-common'
    id 'net.neoforged.moddev'
}

neoForge {
    neoFormVersion = neoform_21_3

    def at = file('src/main/resources/META-INF/accesstransformer.cfg')
    if (at.exists()) accessTransformers = [at.absolutePath]

    parchment {
        minecraftVersion = minecraft_version
        mappingsVersion = parchment_21_3
    }
}

dependencies {
    compileOnly group:'org.spongepowered', name:'mixin', version:'0.8.5'
    testmodCompileOnly sourceSets.main.output
}