modLoader = "javafml"
loaderVersion = "[2,)"
license = "MIT"

[[mods]]
    modId = "resourceconfigapi_test"
    version = "1.0-TEST"
    displayName = "Resource Config API Test"
    authors = "xStopho"
    description = "Testmod for Resource Config API"
    logoFile = "icon_forge.png"