modLoader = "javafml" #mandatory
loaderVersion = "[4,)" #mandatory
license = "${mod_license}"

[[mods]]
    modId = "${mod_id}_testmod"
    version = "${version}"
    displayName = "${mod_name} - Test Mod"
    authors = "${mod_author}"
    description = '''${mod_description}'''

[[dependencies.${mod_id}]]
    modId = "${mod_id}"
    type="required"
    versionRange = "[${version},)"
    ordering = "BEFORE"
    side = "BOTH"
