plugins {
    id 'loader'
    id 'net.neoforged.moddev'
}

def common = project(':common')
dependencies {
    // Remove if testmod isn't needed
    testmodImplementation sourceSets.main.output
    testmodImplementation common.sourceSets.testmod.output
}

neoForge {
    version = neoforge

    def at = file('../common/src/main/resources/META-INF/accesstransformer.cfg')
    if (at.exists()) accessTransformers = [at]

    runs {
        configureEach {
            systemProperty('neoforge.enableGameTestNamespaces', mod_id)
            ideName = "NeoForge ${it.name.capitalize()} (${project.path})"
            gameDirectory = file("../common/runs/${it.name.toLowerCase()}")
        }
        client {
            client()
            sourceSet = sourceSets.testmod
        }
        server {
            server()
            programArguments.add('nogui')
        }
    }
    mods {
        "${mod_id}" { sourceSet sourceSets.main }
        // Remove if testmod isn't needed
        "${mod_id}_test" { sourceSet sourceSets.testmod }
    }
}

// Remove if testmod isn't needed
compileTestmodJava {
    source(project(':common').sourceSets.testmod.allSource)
}

processTestmodResources {
    from file('../common/src/testmod/resources')
}

publishMods {
    file = jar.archiveFile
    modLoaders.addAll("neoforge")
}